### PR TITLE
Prevent server hangs on unconsumed streams.

### LINKED ISSUE #45: MaxFileSizeUploadError can't be caught and crashes the server
Hi!

I have a problem with a custom middleware and the use of the processRequest function.
Here is my custom middleware:

```
try {
    return processRequest(request, options)
                    .then(body => {
                        console.log("body is : ", body);
                        ctx.request.body = body;
                        return next();
                    })
                    .catch(error => {
                        console.log("Error catched : ", error);
                        if (error.status && error.expose) response.status(error.status);
                        return next(error)
                    });
} catch (error) {
    console.log("Error catched bis : ", error);
}
```

If I try to upload a file bigger than the allowed limit, I get the following error and my app crash.

```
events.js:137
      throw er; // Unhandled 'error' event
      ^

MaxFileSizeUploadError: File truncated as it exceeds the size limit.
    at FileStream.file.stream.once (/Volumes/lake/projects/evibe/api-lovejs/node_modules/apollo-upload-server/lib/middleware.js:35:13)
    at Object.onceWrapper (events.js:255:19)
    at FileStream.emit (events.js:160:13)
```

I can't capture the error.
Any idea? 

Thanks :)

### LINKED ISSUE #64: How reject uploading after checking mimetype
Hi, Thanks for Repository.

What is the best efficient way to prevent uploading by checking mimetype (or even filename)?

This is my resolver.

```javascript
resolve: async (obj, {avatar}, ctx) => {
        try {
            const {stream, filename, mimetype, encoding} = await avatar;
            if (mimetype !== 'image/png') {
                console.log('try to close');
                stream.emit('finish');
                return {};
            }
            let { id, path } = await store.itNow({stream, filename});
            return {id, path, filename, mimetype, encoding};
        }
        catch (e) {
            console.log('error', e);
            return {};
        }
    },
```

After uploading a non 'image/png', I got no response.
Im using apolloUploadKoa

### LINKED ISSUE #77: Should handle unexpected streaming errors
The module does not handle unexpected errors happened in the middle of the file streaming. This happens ~4% of the times on 3G networks (last time I checked).

A good example on how to handle them can be found here: https://github.com/expressjs/multer/blob/80ee2f52432cc0c81c93b03c6b0b448af1f626e5/lib/make-middleware.js#L134
```js
        parser.on('error', function (err) {
          pendingWrites.decrement()
          abortWithError(err)
        })
```

Currently, it looks like the module crashes the node.js process. (I do not have proofs of this though.)

### LINKED ISSUE #78: Certain tests failing in Node.js < 10.
I am desperate for help with this. [Certain tests are failing](https://travis-ci.org/jaydenseric/apollo-upload-server/jobs/381536906#L2402), but only in Node.js < 10. With `ava` they used to happen intermittently on my local machine, now we are using `node-tap` I only see them in Travis - testing Node.js v8.5 locally works. Using the Travis Docker image locally I consistently get failures in Node.js v8.5.

The failing tests all relate to situations where the middleware aborts processing to send an early error/response due to a malformed or excessive request.

The errors are `request to http://localhost:{port}/ failed, reason: write EPIPE`. This error is thrown by `node-fetch` when making a test request and the server disconnects without a response. You would expect `node-fetch` would throw a less cryptic error, matching whatever sort of HTTP error `window.fetch` produces but I digress (there are no discussion in `node-fetch` about it, and `got` has a similar behavior). The middleware assertions seem to be working as expected, and the right errors are being thrown. Something about the way the request closes is iffy.

The intention is to reject `processRequest` with an error, setting the response status to the right HTTP error code. That error can be handled by the consumer in latter middleware, or not to have Koa/Express use the error to automatically send the response.

Best practices around this are really murky; with Node.js/Koa/Express out of the box it seems middleware errors only cause a response after the incoming request/upload stream finishes. This is a waste of time and resources; ideally the request is immediately canceled and an early error response is sent. If our middleware takes care of that automatically, it will go against typical Express/Koa middleware design where the consumer has a chance to handle the error themselves in later middleware and send a custom response. I don't even know the best way to cancel the response early anyway, [it's not very straightforward](https://github.com/koajs/koa/issues/879).

I must have spent over a week of effort combined over the past few months trying to work it out, and at this point unless a hero swoops in with a PR I will have to raise the supported Node.js version to 10+.

### LINKED ISSUE #83: Avoid emitting error if upload was not done on closing request
I noticed that when a request ends, if at least one of the uploaded file streams was not consumed, [an error is emitted](https://github.com/jaydenseric/apollo-upload-server/blob/master/src/middleware.mjs#L152). I've found out the hard way, that if you don't subscribe to the `'error'` event on the readable stream, the emission halts the node process and brings down the entire server.

```sh
FileStreamDisconnectUploadError: Request disconnected during file upload stream parsing.
    at IncomingMessage.request.on (/dev/project/node_modules/apollo-upload-server/lib/middleware.js:151:15)
    at IncomingMessage.emit (events.js:182:13)
    at resOnFinish (_http_server.js:564:7)
    at ServerResponse.emit (events.js:187:15)
    at onFinish (_http_outgoing.js:683:10)
    at process._tickCallback (internal/process/next_tick.js:61:11)
Emitted 'error' event at:
    at IncomingMessage.request.on (/dev/project/node_modules/apollo-upload-server/lib/middleware.js:149:32)
    at IncomingMessage.emit (events.js:182:13)
    [... lines matching original stack trace ...]
    at process._tickCallback (internal/process/next_tick.js:61:11)
```

This has the nasty side-effect of potentially allowing **any GraphQL client to send a file under an unexpected field and tear down your server**. I realize this after tracing a bug to the UI where the `file: Upload` field in the mutation was inadvertently being sent as `attachment`. The API server was dying, without any chance of recovering or catching the error.

You can try this using the `apollo-upload-examples`. Just change the [expected `file` field in the `singleUpload` mutation](https://github.com/jaydenseric/apollo-upload-examples/blob/master/api/resolvers.mjs#L54) to any other name on the UI and run the upload.

Is there any way of preventing this kind of behavior?

### PR DESCRIPTION
**Pull request by mike-marcacci**
While the HTTP spec [does support sending a response before the request is finished](https://stackoverflow.com/questions/14250991/is-it-acceptable-for-a-server-to-send-a-http-response-before-the-entire-request) and this behavior is followed by node http and curl, every browser and at least one popular load balancer (GCP) don't support this.

This means that if the server responds before the request stream has finished, the response body will be dropped:

image

If, on the other hand, the server waits before for the request to finish (by dumping the incoming data), the client is able to receive the response:

image

The reason this effects `apollo-upload-client` differently than other upload solutions is twofold:

1. While I prefer the approach of `apollo-upload-server`, most other drop-in file upload middleware waits for all uploads to finish before handing off the request to downstream middleware. This makes it simple, as downstream middleware doesn't have to worry about consuming the entire stream.
2. The downstream middleware is always going to be a `graphql` server, and resolvers are unaware of `Upload`s from other graphql branches (you could hack around this, but it would undo all the ergonomic benefits of `apollo-upload-server`).

Here's my (very typical) use case:

1. Try to upload a large file (or use a slow/throttled connection on a smaller file).
2. Before processing the upload, the graphql resolver checks to see that the user is logged in and throws an error:
    ```js
    if (!session) {
      throw new Error("You must be logged in to save an image.");
    }
    ```

Unfortunately, this is a bit challenging to test, as this is a race: if the upload is fully buffered by node http before the response is sent (small file, local network) then everything works correctly; if it isn't (most real-world cases) then it will fail.

So far I've implemented this in the koa middleware (since that's what I'm using), and will add this to express when I get a chance. I'll also add some tests, but I wanted to drop this off here before somebody else descends the rabbit hole trying to diagnose this.

- Fixes #45, fixes #77, and fixes #83: Correctly handles stream errors.
- Fixes #78: Correctly waits for the request to finish before responding on node >=8.
- Fixes #64: Allow ignoring of an upload without blocking subsequent uploads.

### CODE REVIEW

**Comment by mike-marcacci** [comment]
OK, I've added tests for the koa middleware. The problem with doing this in express is that we're going to need to export 2 different middlewares:

1. before graphql (add the uploads)
2. after graphql (wait to send response)

**Comment by mike-marcacci** [comment]
OK, so the failing tests appear to happen on master using the node v10 and v6. This is good to know, as I was planning to upgrade from v9 shortly! I'm going to look into this as well.

**Comment by mike-marcacci** [comment]
OK, so it looks like #80 fixes master on node v10, so I'm going to go ahead and pull that one into this branch as well.

File: src/middleware.mjs [hunk 1]
```diff
@@ -94,7 +94,7 @@ export const processRequest = (
               operationsPath.set(path, map.get(fieldName).promise)
           }
 
-          resolve(operations)
+          resolve({ operations, map })
```
Comment (jaydenseric) [inline src/middleware.mjs]: This is a breaking change to the API. A fair few people [such as Apollo](https://github.com/apollographql/apollo-server/blob/4405405/packages/apollo-server-express/src/ApolloServer.ts#L12) use `processRequest` directly.

File: package.json [hunk 2]
```diff
@@ -65,9 +65,9 @@
     "build:clean": "rm -r lib; mkdir lib",
     "build:mjs": "BABEL_ESM=1 babel src -d lib --keep-file-extension",
     "build:js": "babel src -d lib",
-    "build:prettier": "prettier 'lib/**/*.{mjs,js}' --write",
+    "build:prettier": "prettier 'src/**/*.{mjs,js}' --write && prettier '*.{json,md}' --write",
     "lint:eslint": "eslint . --ext mjs,js",
-    "lint:prettier": "prettier '**/*.{json,md}' -l",
+    "lint:prettier": "prettier '*.{json,md}' -l",
```
Comment (jaydenseric) [inline package.json]: Ditto, undo.

**Comment by jaydenseric** [comment]
I've just fixed a bug with the tests in master branch (https://github.com/jaydenseric/apollo-upload-server/commit/528216f56186307481c070e2853cc39893fe8b18), might want to rebase.

File: src/middleware.mjs [hunk 3]
```diff
@@ -162,16 +162,39 @@ export const processRequest = (
...
+  } finally {
+    await Promise.all(
+      [...map.values()].map(async upload => {
+        if (upload.done) return
+
+        await upload.promise
+        return new Promise(resolve => {
+          upload.file.stream.on('end', resolve)
+          upload.file.stream.on('error', resolve)
+          if (!upload.file.stream.readableFlowing) upload.file.stream.resume()
```
[the remark this answers is not in the document]
Comment (mike-marcacci) [reply src/middleware.mjs]: We don't want to interfere with any streams that are being consumed, but we do want to run through the rest. Using [readableFlowing](https://nodejs.org/api/stream.html#stream_three_states) let's us know what state the stream is in.

File: src/middleware.mjs (hunk 1 above)
Comment (mike-marcacci) [reply src/middleware.mjs]: That's a good point; I will change how this works.

File: package.json [hunk 4]
```diff
@@ -65,9 +65,9 @@
     "build:clean": "rm -r lib; mkdir lib",
     "build:mjs": "BABEL_ESM=1 babel src -d lib --keep-file-extension",
     "build:js": "babel src -d lib",
-    "build:prettier": "prettier 'lib/**/*.{mjs,js}' --write",
+    "build:prettier": "prettier 'src/**/*.{mjs,js}' --write && prettier '*.{json,md}' --write",
```
[the remark this answers is not in the document]
Comment (mike-marcacci) [reply package.json]: Apologies! Will fix.

File: src/test.mjs [hunk 5]
```diff
@@ -101,6 +102,66 @@ t.test('Single file.', async t => {
   })
 })
 
+t.test('Early response.', async t => {
+  t.jobs = 1
```
[the remark this answers is not in the document]
Comment (mike-marcacci) [reply src/test.mjs]: Great to know! (I'm new to tap.)

File: src/test.mjs [hunk 6]
```diff
@@ -101,6 +102,66 @@ t.test('Single file.', async t => {
...
+
+    await fetch(`http://localhost:${port}`, { method: 'POST', body })
+  }
+
+  await t.test('Koa middleware.', async t => {
+    t.plan(1)
+
+    const data = fs.readFileSync(TEST_FILE_PATH)
+
+    var requestHasFinished = false
```
[the remark this answers is not in the document]
Comment (mike-marcacci) [reply src/test.mjs]: Sounds good; not to get side-tracked, but is there a benefit to `let` over `var` for top-level function-scoped variables, other than stylistic consistency?

File: src/test.mjs [hunk 7]
```diff
@@ -101,6 +102,66 @@ t.test('Single file.', async t => {
...
+    const stream = new Readable()
+    stream.path = TEST_FILE_PATH
+    stream._read = () => {}
```
[the remark this answers is not in the document]
Comment (mike-marcacci) [reply src/test.mjs]: This is the old, but still-supported way of implementing streams in node (for Streams 2, which is still the current implementation).

File: src/test.mjs [hunk 8]
```diff
@@ -101,6 +102,66 @@ t.test('Single file.', async t => {
...
+    const promise = testRequest(port, stream).then(
+      () => {
+        t.equals(
+          requestHasFinished,
+          true,
+          'The server should not respond before the request has finished'
+        )
+      },
+      err => {
+        throw err
```
[the remark this answers is not in the document]
Comment (mike-marcacci) [reply src/test.mjs]: Totally!

File: src/test.mjs [hunk 9]
```diff
@@ -101,6 +102,66 @@ t.test('Single file.', async t => {
...
+      }
+    )
+
+    setTimeout(() => {
+      stream.push(data)
+      stream.push(null)
+    }, 10)
+
+    return promise
```
[the remark this answers is not in the document]
Comment (mike-marcacci) [reply src/test.mjs]: Sounds good!

**Comment by jaydenseric** [comment]
@mike-marcacci really appreciate your help 👏

I'm on the Apollo slack (and I can see you're on there too), so feel free to chat about any of this stuff, either publicly in the `#uploads` channel or via DM. My timezone is Melbourne, Australia.

**Comment by mike-marcacci** [comment]
OK, well, as an update, I wasn't able to get any success with http2, but my real world use case is complex (reverse proxies, etc) so I thought I should go back to first principles. I created a test to try against the browsers on my laptop:

https://gist.github.com/mike-marcacci/5c7f435d51240feb8a871ab348a00dfd

And I can't seem to reproduce the issue on http, https or http2, so I've got to keep digging. I'll post back when I find something.

**Comment by mike-marcacci** [comment]
OK, so after a ton of investigation, I've learned a lot :) I created a [set of tests](https://github.com/mike-marcacci/node-http-streams-tests) to demonstrate node's HTTP behavior under a variety of scenarios, and read the relevant source for http, streams, koa, and busboy.

It turns out that my premise here was wrong, although my solution (accidentally) may be correct. It turns out that node *does* wait for an HTTP request to finish before sending the HTTP response. This is true on HTTP-1.1, HTTP-1.1 over TLS, and HTTP-2, as shown [here](https://github.com/mike-marcacci/node-http-streams-tests/blob/master/01_node.js). By default,  if `req` has no consumers when data is sent to `res`, node will send its contents to the void *before responding*. If however, a consumer exists, node will wait indefinitely.

The symptom that I was seeing was actually a due to this "hanging" *in my app's particular context*: My app sits behind a proxy which was dropping the idle connection (this behavior was consistent across `node-http`, `haproxy`, and GCP's HTTP load balancer).

The solution, though, is the same: `apollo-upload-server` MUST prevent hanging, because it's impossible to downstream. Take this example, where `$photo` is an upload:

```graphql
query {
  me: {
    id
    friends (whoLookLike: $photo) {
      id
      name
    }
  }
}
```

The resolver for `me` might throw an error like "You are not logged in!" or encounter an error when querying the database. In these cases, the resolver for `friends` is never called and never has an opportunity to continue the upload stream!

This will result in no response making it back to the client (either hanging forever, or getting killed by a proxy). There are a couple ways to fix this:

### Solution 1
The simplest thing to unpipe busboy and resume the request after resolvers have finished:

```
// ...
  await next()

  ctx.req.unpipe(parser)
  ctx.req.resume()
  parser.destroy()
// ...
```

This has the advantage of being the fastest, since we won't be decoding unused files. However, it does mean that resolvers who *do* use an upload can't return early and expect to receive the rest of its contents. This is already handled quite nicely with the `FileStreamDisconnectUploadError`.

### Solution 2
This is basically what I implemented here. We simply make sure to `.resume()` every upload that isn't actively flowing. This means that the entire request will be decoded, but the caveat from Solution 1 doesn't apply.

---

One other scenario that I have to test... it seems possible to me that the following query is unsolvable with the current implementation:

```graphql
query {
  me: {
    id
    friends (whoLookLike: $photo1) {
      id
      name
    }
  }
  searchPeople(whoLookLike: $photo2) {
    id
    name
  }
}
```

Assuming that `$photo1` is never accessed... will the promise for `$photo2` ever resolve? I don't think ever will, and will end in a forever hanging request. Again, I need to test this.

**Comment by mike-marcacci** [comment]
OK, so I added a test for my theory on possible infinite hanging... and I was sadly correct. Do note, though, that this bug is bypassed if the entirety of `$photo1` exists in the same TCP packet as `$photo2`.

I'll work on a fix for this, and incorporate it into this PR, if you don't mind (rather than create another PR, as these issues are related).

**Comment by mike-marcacci** [comment]
Alright! And it's fixed :)

Instead of passing busboy's `FileStream` directly to the graphql body, I created an intermediary `UploadStream` that allows busboy to continue parsing the request uninterrupted. This means:

1. Streams will parse faster, since `$photo2` doesn't have to wait for the resolver of `$photo1` to finish.
2. The request will never get stuck in a perpetual `await` because some resolver was never reached.
3. An upload-handling resolver doesn't have to worry about consuming a stream it doesn't care about (ie, it can just return early)
4. We actually eliminate a potential memory and file descriptor leak from unclosed idle connections and all their resources.

I'm going to go ahead and close #80, as its changes are merged in here, and some of the strategy has changed.

Please let me know if you have any concerns!

Cheers,
Mike

**Comment by mike-marcacci** [comment]
Well, there’s more to this... I’ll dump another big realization and change shortly.

**Comment by mike-marcacci** [comment]
So, I went to test all these changes in my real-world project, and encountered some issues:

1. The tested behavior changes when a file is larger than the stream `highWaterMark`.
2. Node actually behaves slightly (but importantly) differently from what I described above, and its behavior changes significantly depending on whether the HTTP connection is set as `close` vs `keep-alive`.

### Bufferring To Files
First to address the issue of `highWaterMark` being exceeded. My tests for the solution described [here](#issuecomment-396002020) used a file that could fit entirely into the memory buffer of the `UploadStream` I created. However, when using real (large) files, node streams (correctly) detected the backpressure from this unconsumed duplex stream and paused everything upstream (including the HTTP request), which brought back our indefinite wait.

So instead, I wrote [fs-capacitor](https://github.com/mike-marcacci/fs-capacitor), which acts like a duplex stream that buffers to the filesystem (instead of memory) and importantly *doesn't* propagate backpressure upstream. This means that it can consume the entire upload without interruption, even if it is unconsumed. This will have some performance cost, as it's using the filesystem where it previously used RAM, but this is a worthy compromise for correctness and avoiding indefinite hangs. Also, with the previlance of SSDs the performance difference is quite small, and given the fact that unix streams (including the incoming TCP connection) buffer to the filesystem, this probably won't be a bottleneck.

### Node & HTTP
My previous revalations weren't entirely correct (and honestly, I bet neither are these... but they're based on tests so hopefully they're a bit closer to reality!).

It turns out that whenever `res.end()` is called, `req` emits a close event, which is indistinguishable (to my tests at least) from an early close by the client.

At this time, if the HTTP connection is `close` (which was the default downstream mode of all the proxies I tested), the connection will be closed even though the request is incomplete.

On the other hand, if the HTTP connection is `keep-alive` (which can be forced by setting the header, like `ctx.set('Connection', 'keep-alive')`) the request data will continue to flow after `res.end()` is called.

One solution is simply to force `keep-alive`, which is simpler than waiting to send `res.end()`. But this has 2 problems which I haven't yet solved (and probably won't have time to, since I've been in this rabbit hole far too long already):

1. I can't distinguish between an early close initiated by the client (I never see the `abort` event fire, even when I think it should) and one initiated by `res.end()`
2. Not all clients (or proxies) support `keep-alive`. While it's likely that the vast majority do, common setups such as `node-http-proxy` require additional configuration to support this. In this situation, all in-progress uploads get terminated, and the response never makes it to the client.

The second solution is to wait for the parser to finish. This is the route I've taken, but it requires a change to the API since it's not enough for `processRequest` to resolve the just the body.

---

I wrote [fs-capacitor](https://github.com/mike-marcacci/fs-capacitor) specifically for `apollo-upload-server` and tested it quite extensively in that context, but realized it belongs in its own package. I haven't added tests or docs for it yet, since I'm super behind on not-rabbit-hole work ;-) But I'll add them when I have time.

**Comment by jaydenseric** [comment]
Wow! Love the depth 🙌

It's a public holiday long weekend here in Australia (Queen's birthday), so I hope to immerse in your findings early this week.

File: src/test.mjs [hunk 10]
```diff
@@ -11,17 +13,25 @@ import {
...
+
+// The max TCP packet size is 64KB, so this file is guaranteed to arrive
+// in multiple chunks. It is a public domain image retreived from:
+// https://commons.wikimedia.org/wiki/File:Belvedere_Apollo_Pio-Clementino_Inv1015.jpg
+const TEST_FILE_PATH_JPG = 'Belvedere_Apollo_Pio-Clementino_Inv1015.jpg'
 
 const startServer = (t, app) =>
   new Promise((resolve, reject) => {
-    app.listen(function(error) {
+    app.listen(undefined, 'localhost', function(error) {
```
Comment (jaydenseric) [inline src/test.mjs]: Is this change necessary, what does it do differently?

Comment (mike-marcacci) [reply src/test.mjs]: By default, node listens on all available hosts, which exposes the port to the network; this doesn't really matter, but it's probably best practice to just listen on `localhost`. The reason I changed it is that every time the test would run, I'd get multiple popups from my Mac's firewall asking if I wanted to allow incoming connections to that port, which made it quite annoying to work :)

**Comment by mike-marcacci** [comment]
OK, this is *finally* ready.

- fix #45, #77, fix #83 - correctly handles stream errors
- fix #78 - correctly waits for the request to finish before responding on node >=8
- fix #64 - allow ignoring of an upload without blocking subsequent uploads

### To Do
- [x] describe changes in changelog.md
- [x] update docs in readme.md
- [x] test in real-world use case
- [ ] review by @jaydenseric
- [ ] merge into master
- [ ] bump "minor" version
- [ ] publish to NPM

File: readme.md [hunk 11]
```diff
@@ -21,6 +21,7 @@ Add the middleware just before [graphql-server](https://github.com/apollographql
 - `maxFieldSize` (integer): Max allowed non-file multipart form field size in bytes; enough for your queries (default: 1 MB).
 - `maxFileSize` (integer): Max allowed file size in bytes (default: Infinity).
 - `maxFiles` (integer): Max allowed number of files (default: Infinity).
+- `errorHandler` (function): This function is attached to the `error` event of each file stream. (default: () => {})).
```
Comment (jaydenseric) [inline readme.md]: Maybe we don't need to expose this as an option. It's not very intuitive to users why the option exists since we document people should have an error listener on file streams in resolvers; they might wonder when should which be used, and why. Also, other than perhaps logging, I can't think of a good use case?

File: package.json [hunk 12]
```diff
@@ -1,6 +1,6 @@
 {
-  "name": "apollo-upload-server",
-  "version": "5.0.0",
+  "name": "@boltline/apollo-upload-server",
```
[the remark this answers is not in the document]
Comment (mike-marcacci) [reply package.json]: Very much :( that's the "public but not advertised" fork I pushed to test this in production

File: readme.md (hunk 11 above)
Comment (mike-marcacci) [reply readme.md]: Ya, the only real case here is logging. I don't mind getting rid of it, or changing the name to something like "errorLogger" or "onError" so it's less confusing.

Comment (jaydenseric) [reply readme.md]: I vote removing it; we have the diff for how to add it later as an enhancement if people really want it.

File: src/middleware.mjs [hunk 13]
```diff
@@ -22,25 +25,30 @@ class Upload {
           this.done = true
```
Comment (jaydenseric) [inline src/middleware.mjs]: It looks like this is not used anywhere anymore?

Comment (mike-marcacci) [reply src/middleware.mjs]: Yep, that's correct! Removed.

**Comment by ForsakenHarmony** [comment]
I need this 👀

**Comment by terion-name** [comment]
HURRAY! @jaydenseric when to expect this to be tagged on npm?

**Comment by jaydenseric** [comment]
@terion-name I have a few minor things to sneak in, then publish hopefully within the next day. The new version will likely be a semver major, due to the raised min Node.js version. If you use a recent Node.js version it should be a painless upgrade.

File: src/middleware.mjs [hunk 14]
```diff
@@ -147,28 +209,42 @@ export const processRequest = (
...
+    await finished
+  }
 }
 
 export const apolloUploadExpress = options => (request, response, next) => {
   if (!request.is('multipart/form-data')) return next()
+
+  const finished = new Promise(resolve => request.on('end', resolve))
+  const { send } = response
+  response.send = (...args) => {
```
Comment (jaydenseric) [inline src/middleware.mjs]: Is this monkey patching the `send` method for all following express middleware? This seems pretty cheeky.

Comment (mike-marcacci) [reply src/middleware.mjs]: Ya, this a really ugly thing to do, but it’s the only way I know to “wrap” child middleware in express/connect without requiring them to be aware of the parent middleware... I’ve reluctantly used this pattern in the past and haven’t really run into issues, but if you know of any other way to do this, I’d love to learn!

**Comment by jaydenseric** [comment]
@mike-marcacci do you know what might be causing these errors? https://travis-ci.org/jaydenseric/apollo-upload-server/jobs/402915414#L2165

**Comment by mike-marcacci** [comment]
I’m going to assume you’re referring to the “Parse Error” in the logs (Travis line links are apparently messed up on mobile). I don’t know off the top of my head, but I suspect those are a case where we’re testing an aborted request, and we propagate our custom events while busboy emits a parse error. I’m not sure how those would get in the logs, but I assume there’s something special going on with Tap. I’ll loot at these tomorrow.

File: src/middleware.mjs (hunk 14 above)
Comment (koresar) [reply src/middleware.mjs]: Of the top of my head it might break `res.write()`: https://stackoverflow.com/questions/44692048/what-is-the-difference-between-res-send-and-res-write-in-express

But I don't know any existing code bases (out of dozens I overview or maintain) which use `res.write()` with express.js.

**Comment by ForsakenHarmony** [comment]
when are you gonna release this?

**Comment by jaydenseric** [comment]
@ForsakenHarmony A few unanticipated issues have popped up. Once we know what is causing the errors [mentioned above](https://github.com/jaydenseric/apollo-upload-server/pull/81#issuecomment-404745965), and once https://github.com/jaydenseric/apollo-upload-server/pull/89#issuecomment-404755081 is fixed and merged we can publish v6.0.0-alpha.1.

Help resolving these blockers is the fastest path to a release, otherwise it is mostly up to @mike-marcacci's availability. If there is no movement this week I will ***try*** to take a day or more off from project work to see what more I can do.

Earlier versions had a simpler (although less efficient) approach using formidable and temp files. I would love to have more Node.js stream experts come on to the project as collaborators.

File: src/middleware.mjs (hunk 14 above)
Comment (mike-marcacci) [reply src/middleware.mjs]: @koresar you're definitely correct that calling `res.write()` could break some assumptions, and also that doing so is a kind of escape hatch from express. In fact, calling `ctx.req.write()` would break koa as well.

**Comment by mike-marcacci** [comment]
@ForsakenHarmony @jaydenseric you're in luck, I've got some time here today :) we didn't have as great cell coverage in our last locations as we had expected. Stay tuned!

**Comment by jaydenseric** [comment]
Published in [v6.0.0-alpha.1](https://github.com/jaydenseric/apollo-upload-server/releases/tag/v6.0.0-alpha.1) 🎉

**Comment by ForsakenHarmony** [comment]
seems like you published it as a normal release on npm not alpha/beta, just as a heads up

**Comment by mike-marcacci** [comment]
Thanks for the heads-up @ForsakenHarmony. You're right: it looks like @jaydenseric will need to update npm's "latest" tag to point back at 5.0.0.

**Comment by jaydenseric** [comment]
Thats deliberate actually; v6.0.0-alpha.1 is more stable than v5.0.0 and everyone who can (given the few breaking changes) is advised to update.

**Comment by mike-marcacci** [comment]
Aah I see. Good strategy!
